import json
import io
import csv
from flask import Blueprint, render_template, request, redirect, url_for, flash, Response, g
from app.auth.routes import login_required
from app.database import get_db
from app.projects.engine import rank_employees_for_project
from app.projects.ai_service import get_ai_explanations
from app.employees.routes import process_employee_csv

bp = Blueprint('projects', __name__, url_prefix='/projects')

@bp.route('/', methods=('GET',))
@login_required
def index():
    """List project entry form and previous projects generated by the current user."""
    db = get_db()
    
    # Query projects created by this user
    try:
        # Fetch projects along with assignments count using PostgREST embedding
        res = db.table('projects').select('*, assignments(id)').eq('created_by', g.user['id']).order('created_at', desc=True).execute()
        raw_projects = res.data
        
        projects = []
        for p in raw_projects:
            p_copy = dict(p)
            p_copy['assigned_count'] = len(p.get('assignments', []))
            projects.append(p_copy)
    except Exception as e:
        print(f"Error fetching projects: {e}")
        projects = []
    
    return render_template('projects.html', projects=projects)

@bp.route('/new', methods=('POST',))
@login_required
def new_project():
    """Create a new project, run scoring engine to assign employees, get AI insights, and redirect."""
    name = request.form.get('name', '').strip()
    description = request.form.get('description', '').strip()
    duration = request.form.get('duration', '').strip()
    team_size_str = request.form.get('team_size', '1').strip()
    technologies = request.form.get('technologies', '').strip()
    preferred_roles = request.form.get('preferred_roles', '').strip()
    
    error = None
    
    if not name:
        error = 'Project Name is required.'
    elif not description:
        error = 'Project Description is required.'
    elif not duration:
        error = 'Duration is required.'
        
    try:
        team_size = int(team_size_str)
        if team_size <= 0:
            error = 'Team Size must be a positive integer.'
    except ValueError:
        error = 'Team Size must be a valid number.'
        
    db = get_db()
    
    # Check for optional CSV file upload to seed/update employee list inside the form
    if 'employee_csv' in request.files:
        csv_file = request.files['employee_csv']
        if csv_file and csv_file.filename != '':
            if csv_file.filename.endswith('.csv'):
                try:
                    stream = io.StringIO(csv_file.stream.read().decode("UTF8"), newline=None)
                    imported, errors = process_employee_csv(stream, db)
                    if errors:
                        flash(f"CSV import completed with warnings: {'; '.join(errors[:3])}", 'warning')
                    else:
                        flash(f"Imported {imported} employees successfully from project form.", 'success')
                except Exception as e:
                    flash(f"Failed to parse employee CSV: {str(e)}", 'error')
            else:
                flash("Uploaded file must be a CSV.", 'error')
    
    # Verify there are employees to assign
    try:
        emp_res = db.table('employees').select('id', count='exact').execute()
        employee_count = emp_res.count if emp_res.count is not None else len(emp_res.data)
        if employee_count == 0:
            error = 'No employees available in the database. Please import employee CSV data first.'
    except Exception as e:
        error = f"Database error checking employees: {e}"
        
    if error is not None:
        flash(error, 'error')
        return redirect(url_for('projects.index'))
        
    try:
        # 1. Insert Project into DB
        proj_insert = db.table('projects').insert({
            'name': name,
            'description': description,
            'duration': duration,
            'team_size': team_size,
            'technologies': technologies,
            'preferred_roles': preferred_roles,
            'created_by': g.user['id']
        }).execute()
        
        project = proj_insert.data[0]
        project_id = project['id']
        
        # 2. Retrieve All Employees
        emp_res = db.table('employees').select('*').execute()
        emp_dicts = emp_res.data
        
        # 3. Score and Rank Employees
        ranked_employees = rank_employees_for_project(emp_dicts, project)
        
        # Select the top N employees
        selected_team_with_scores = ranked_employees[:team_size]
        
        # 4. Save Assignments in Database
        assignments_to_insert = []
        for emp, scores in selected_team_with_scores:
            assignments_to_insert.append({
                'project_id': project_id,
                'employee_id': emp['id'],
                'match_score': scores['total_score']
            })
            
        if assignments_to_insert:
            db.table('assignments').insert(assignments_to_insert).execute()
        
        # 5. Generate AI Explanations
        selected_emp_dicts = [emp for emp, _ in selected_team_with_scores]
        ai_payload = get_ai_explanations(project, selected_emp_dicts)
        
        # 6. Cache AI Explanations JSON back to Project
        db.table('projects').update({
            'ai_explanation': json.dumps(ai_payload)
        }).eq('id', project_id).execute()
        
        flash('Project team assignments generated successfully!', 'success')
        return redirect(url_for('projects.results', project_id=project_id))
        
    except Exception as e:
        flash(f"An error occurred while generating assignments: {str(e)}", 'error')
        return redirect(url_for('projects.index'))

@bp.route('/<int:project_id>/results', methods=('GET',))
@login_required
def results(project_id):
    """Display the assignment results page with team scores and AI justifications."""
    db = get_db()
    
    # Get project info
    try:
        proj_res = db.table('projects').select('*').eq('id', project_id).eq('created_by', g.user['id']).execute()
        if not proj_res.data:
            flash('Project not found.', 'error')
            return redirect(url_for('projects.index'))
        project = proj_res.data[0]
        
        # Get assignments joined with employee info
        assign_res = db.table('assignments').select('*, employees(*)').eq('project_id', project_id).execute()
        
        # Flatten structure and sort by match_score DESC
        assignments = []
        for a in assign_res.data:
            emp_data = a.get('employees', {})
            emp_data['match_score'] = a['match_score']
            assignments.append(emp_data)
            
        assignments.sort(key=lambda x: x['match_score'], reverse=True)
            
    except Exception as e:
        flash(f"Error fetching results: {e}", 'error')
        return redirect(url_for('projects.index'))
        
    if not assignments:
        flash('No assignments found for this project.', 'error')
        return redirect(url_for('projects.index'))
        
    # Calculate aggregate team compatibility score (average score of selected members)
    total_match = sum(a['match_score'] for a in assignments)
    team_match_percentage = total_match / len(assignments) if assignments else 0
    
    # Parse cached AI explanation
    ai_insights = {}
    if project.get('ai_explanation'):
        try:
            ai_insights = json.loads(project['ai_explanation'])
        except Exception:
            pass
            
    # Compute aggregate team composition count by role
    composition = {}
    for a in assignments:
        role = a['role']
        composition[role] = composition.get(role, 0) + 1
        
    return render_template(
        'results.html',
        project=project,
        assignments=assignments,
        team_match_percentage=team_match_percentage,
        composition=composition,
        ai_insights=ai_insights
    )

@bp.route('/<int:project_id>/export', methods=('GET',))
@login_required
def export_csv(project_id):
    """Export the project results and AI insights as a downloadable CSV file."""
    db = get_db()
    
    try:
        proj_res = db.table('projects').select('*').eq('id', project_id).eq('created_by', g.user['id']).execute()
        if not proj_res.data:
            return "Project not found", 404
        project = proj_res.data[0]
        
        assign_res = db.table('assignments').select('*, employees(*)').eq('project_id', project_id).execute()
        assignments = []
        for a in assign_res.data:
            emp_data = a.get('employees', {})
            emp_data['match_score'] = a['match_score']
            assignments.append(emp_data)
        assignments.sort(key=lambda x: x['match_score'], reverse=True)
        
    except Exception as e:
        return f"Database error: {e}", 500
    
    # Parse cached AI insights
    ai_insights = {}
    if project.get('ai_explanation'):
        try:
            ai_insights = json.loads(project['ai_explanation'])
        except Exception:
            pass
            
    indiv_reasons = ai_insights.get('individual_explanations', {})
    
    # Create in-memory CSV buffer
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Write Project Header Section
    writer.writerow(["PROJECT ASSIGNMENT SUMMARY REPORT"])
    writer.writerow([])
    writer.writerow(["Project Details"])
    writer.writerow(["Project Name", project['name']])
    writer.writerow(["Description", project['description']])
    writer.writerow(["Duration", project['duration']])
    writer.writerow(["Target Team Size", project['team_size']])
    writer.writerow(["Tech Preferences", project['technologies']])
    writer.writerow(["Preferred Roles", project['preferred_roles']])
    writer.writerow([])
    
    # Write Team Composition Section
    writer.writerow(["Assigned Team Members"])
    writer.writerow([
        "Employee ID", "Name", "Role", "Skills", 
        "Experience (Years)", "Availability", "Performance Score", 
        "Match Score", "AI Selection Reason"
    ])
    
    for a in assignments:
        emp_id = a.get('employee_id', '')
        reason = indiv_reasons.get(str(emp_id), indiv_reasons.get(emp_id, "N/A"))
        writer.writerow([
            emp_id,
            a.get('name', ''),
            a.get('role', ''),
            a.get('skills', ''),
            a.get('experience', ''),
            a.get('availability', ''),
            a.get('performance_score', ''),
            f"{a['match_score']:.1f}%",
            reason
        ])
    writer.writerow([])
    
    # Write AI Insights Section
    writer.writerow(["AI System Team Insights"])
    writer.writerow(["Team Strengths", ai_insights.get('team_strengths', 'N/A')])
    writer.writerow(["Delivery Risks", ai_insights.get('delivery_risks', 'N/A')])
    writer.writerow(["Missing Skills", ", ".join(ai_insights.get('missing_skills', [])) or 'None'])
    writer.writerow(["Actionable Recommendations", ai_insights.get('recommendations', 'N/A')])
    
    # Configure Response
    response_data = output.getvalue()
    output.close()
    
    filename = f"ProjectAssign_{project['name'].replace(' ', '_')}_Report.csv"
    
    return Response(
        response_data,
        mimetype="text/csv",
        headers={"Content-disposition": f"attachment; filename={filename}"}
    )

@bp.route('/<int:project_id>/delete', methods=('POST',))
@login_required
def delete_project(project_id):
    """Delete a project and cascade clear assignments."""
    db = get_db()
    try:
        db.table('projects').delete().eq('id', project_id).eq('created_by', g.user['id']).execute()
        flash('Project deleted.', 'info')
    except Exception as e:
        flash(f'Error deleting project: {e}', 'error')
    return redirect(url_for('projects.index'))
